# Generated by Django 3.0.8 on 2021-01-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
